profession:
  class: sfDoctrineRouteCollection
  options:
    model:                profession
    module:               profession
    prefix_path:          /profession
    column:               id
    with_wildcard_routes: true

revision:
  class: sfDoctrineRouteCollection
  options:
    model:                Revision
    module:               revisions
    prefix_path:          /revisions
    column:               id
    with_wildcard_routes: true

revision_state:
  class: sfDoctrineRouteCollection
  options:
    model:                RevisionState
    module:               revision_states
    prefix_path:          /revision_states
    column:               id
    with_wildcard_routes: true

procedure:
  class: sfDoctrineRouteCollection
  options:
    model:                Procedure
    module:               procedures
    prefix_path:          /procedures
    column:               id
    with_wildcard_routes: true

sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               permissions
    prefix_path:          /permissions
    column:               id
    with_wildcard_routes: true

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               groups
    prefix_path:          /groups
    column:               id
    with_wildcard_routes: true

profile:
  class: sfDoctrineRouteCollection
  options:
    model:                Profile
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               users
    prefix_path:          /users
    column:               id
    with_wildcard_routes: true

formu:
  class: sfDoctrineRouteCollection
  options:
    model:                Formu
    module:               formus
    prefix_path:          /formus
    column:               id
    with_wildcard_routes: true

form:
  class: sfDoctrineRouteCollection
  options:
    model:                Form
    module:               forms
    prefix_path:          /forms
    column:               id
    with_wildcard_routes: true

item:
  class: sfDoctrineRouteCollection
  options:
    model:                Item
    module:               items
    prefix_path:          /items
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: procedures, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
