generator:
  class:                          sfDoctrineGenerator
  param:
    model_class:                  Procedure
    theme:                        mooDoo.2
    non_verbose_templates:        true
    with_show:                    false
    singular:                     ~
    plural:                       ~
    route_prefix:                 procedure
    with_doctrine_route:          true
    actions_base_class:           sfActions

    config:
      actions: ~
      fields:  ~

      list:
        fields:
          revisions_count:          { label: R }
        display:                    [ formu, cadastral_data, creator, revisions_count, _state, dossier, is_finished, _created_at ]
        object_actions:
          _detail:                  ~
          _delete:                  ~
          _edit:                    ~

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
