generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Item
    theme:                 mooDoo.2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        group_acronym:    { label: Grupo }
        formus_list:      { label: Formularios al que pertenece }
      list:
        display:          [ group_acronym, title ]
      filter:  ~
      form:    ~
      edit:
        title: Editar Item
      new:
        title: Nuevo Item
        
