generator:
  class:                          sfDoctrineGenerator
  param:
    model_class:                  sfGuardUser
    theme:                        mooDoo.2
    non_verbose_templates:        true
    with_show:                    false
    singular:                     ~
    plural:                       ~
    route_prefix:                 sf_guard_user
    with_doctrine_route:          true
    actions_base_class:           sfActions

    config:
      actions: ~
      fields:  ~

      list:
        display:                      [ _mugshot, username, complete_name, is_active, _created_at, _last_login, _tipo ]

      filter:  ~
      form:
        class:                        sfMooDooUserForm
        display:
          "Account":                  [ username, password, password_again ]
          #"Profile":                  [ Profile ]
          "Permissions and groups":   [ is_active, is_super_admin, groups_list, permissions_list ]

      edit:    ~
      new:     ~